services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - app-net
    volumes:
      - ./server:/app/server
    depends_on:
      db:
        condition: service_healthy
  
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app/client
    ports:
      - "5173:5173"
    networks:
      - app-net
    depends_on:
      - server

  db:
    container_name: db
    image: mysql
    ports:
      - "3306"
    networks:
      - app-net
    environment:  
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "chat"
      # MYSQL_DATA: /data
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10    
networks:
  app-net:
